{
 "title": "Arista",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Front Panel",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "current",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "description" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sensor",
     "query": "SELECT max(\"entPhySensorValue\") / 10 FROM \"sensor\" WHERE (\"agent_host\" = '192.168.1.7' AND \"description\" = 'Front-panel temp sensor') AND $timeFilter GROUP BY time($__interval), \"description\" fill(null)",
     "select": [
      [
       { "params": [ "entPhySensorValue" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "/ 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "192.168.1.7" },
      { "condition": "AND", "key": "description", "operator": "=", "value": "Front-panel temp sensor" }
     ]
    },
    {
     "alias": "warning",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sensor",
     "select": [
      [
       { "params": [ "highWarning" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "192.168.1.7" },
      { "condition": "AND", "key": "description", "operator": "=", "value": "Front-panel temp sensor" }
     ]
    },
    {
     "alias": "critical",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sensor",
     "select": [
      [
       { "params": [ "highCritical" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "192.168.1.7" },
      { "condition": "AND", "key": "description", "operator": "=", "value": "Front-panel temp sensor" }
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "current",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sensor",
     "query": "SELECT max(\"entPhySensorValue\")  / 10 FROM \"sensor\" WHERE (\"agent_host\" = '192.168.1.7' AND \"description\" = 'Cpu temp sensor') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "entPhySensorValue" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "192.168.1.7" },
      { "condition": "AND", "key": "description", "operator": "=", "value": "Cpu temp sensor" }
     ]
    },
    {
     "alias": "warning",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sensor",
     "query": "SELECT max(\"highWarning\")  / 10 FROM \"sensor\" WHERE (\"agent_host\" = '192.168.1.7' AND \"description\" = 'Cpu temp sensor') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "highWarning" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "192.168.1.7" },
      { "condition": "AND", "key": "description", "operator": "=", "value": "Cpu temp sensor" }
     ]
    },
    {
     "alias": "critical",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sensor",
     "select": [
      [
       { "params": [ "highCritical" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "192.168.1.7" },
      { "condition": "AND", "key": "description", "operator": "=", "value": "Cpu temp sensor" }
     ]
    },
    {
     "alias": "$tag_description",
     "groupBy": [
      { "params": [ "$__interval*50" ], "type": "time" },
      { "params": [ "description" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sensor",
     "select": [
      [
       { "params": [ "entPhySensorValue" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "192.168.1.7" },
      { "condition": "AND", "key": "sensorType", "operator": "=", "value": "10" }
     ]
    }
   ]
  },
  {
   "title": "Input Voltages",
   "type": "graph",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "alias": "orange",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sensor",
     "select": [
      [
       { "params": [ "entPhySensorValue" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "192.168.1.7" },
      { "condition": "AND", "key": "index", "operator": "=", "value": "100711104" }
     ]
    },
    {
     "alias": "white",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sensor",
     "select": [
      [
       { "params": [ "entPhySensorValue" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "192.168.1.7" },
      { "condition": "AND", "key": "index", "operator": "=", "value": "100721104" }
     ]
    }
   ]
  }
 ]
}