{
 "title": "Drinka PC",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "SHOW TAG VALUES WITH KEY = \"host\" WHERE app = 'ohm'\n"
   },
   {
    "name": "power",
    "query": "show tag values from Power with key = hardware_type WHERE app = 'ohm'"
   },
   {
    "name": "temperature",
    "query": "show tag values from Temperature with key = hardware_type WHERE app = 'ohm'"
   },
   {
    "name": "volts",
    "query": "show tag values from Voltage with key = hardware_type WHERE app = 'ohm'"
   },
   {
    "name": "network",
    "query": "show tag values with key = hardware WHERE hardware_type = 'NIC' and app = 'ohm'"
   },
   {
    "name": "fan",
    "query": "show tag values from Fan with key = hardware_type WHERE app = 'ohm'"
   },
   {
    "name": "control",
    "query": "show tag values from Control with key = hardware_type WHERE app = 'ohm'"
   },
   {
    "name": "hertz",
    "query": "show tag values from Clock with key = hardware_type WHERE app = 'ohm'"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Load",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_sensor",
     "groupBy": [
      { "params": [ "$__interval*10" ], "type": "time" },
      { "params": [ "sensor" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Load",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "app", "operator": "=", "value": "ohm" },
      { "condition": "AND", "key": "hardware_type", "operator": "=", "value": "CPU" },
      { "condition": "AND", "key": "sensor", "operator": "!=", "value": "CPU Total" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU Wattage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "$tag_sensor",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sensor" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Power",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "app", "operator": "=", "value": "ohm" },
      { "condition": "AND", "key": "hardware_type", "operator": "=", "value": "CPU" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "sensor", "operator": "=", "value": "CPU Package" }
     ]
    }
   ]
  },
  {
   "title": "CPU Frequencies",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "alias": "$tag_sensor",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "sensor" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Clock",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "* 1000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "app", "operator": "=", "value": "ohm" },
      { "condition": "AND", "key": "hardware_type", "operator": "=", "value": "CPU" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "sensor", "operator": "!=", "value": "Bus Speed" }
     ]
    }
   ]
  },
  {
   "title": "CPU Temperatures",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "$tag_sensor",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sensor" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "app", "operator": "=", "value": "ohm" },
      { "condition": "AND", "key": "hardware_type", "operator": "=", "value": "CPU" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "sensor", "operator": "!~", "value": "/TjMax/" },
      { "condition": "AND", "key": "sensor", "operator": "!=", "value": "Core Average" },
      { "condition": "AND", "key": "sensor", "operator": "!=", "value": "Core Max" }
     ]
    }
   ]
  },
  {
   "title": "Disk Temperatures",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "$tag_sensor",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sensor" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "app", "operator": "=", "value": "ohm" },
      { "condition": "AND", "key": "hardware_type", "operator": "=", "value": "HDD" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  }
 ]
}