{
 "title": "Nest",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Location",
    "query": "SHOW TAG VALUES WITH KEY=\"location\""
   }
  ]
 },
 "panels": [
  {
   "title": "House Temperature",
   "type": "graph",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "Master-Bedroom",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "nest_remote",
     "select": [
      [
       { "params": [ "current_temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=", "value": "Master-Bedroom" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$Location$/" }
     ]
    },
    {
     "alias": "Kitchen-Hallway",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "nest",
     "select": [
      [
       { "params": [ "current_temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=", "value": "Kitchen-Hallway" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$Location$/" }
     ]
    },
    {
     "alias": "Kids-Room",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "nest_remote",
     "select": [
      [
       { "params": [ "current_temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=", "value": "Kids-Room" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$Location$/" }
     ]
    },
    {
     "alias": "target",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "nest",
     "select": [
      [
       { "params": [ "target_temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=", "value": "Kitchen-Hallway" }
     ]
    }
   ]
  },
  {
   "title": "HVAC Control",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "alias": "Fan",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "nest",
     "select": [
      [
       { "params": [ "fan_control_state" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=", "value": "Kitchen-Hallway" }
     ]
    },
    {
     "alias": "Heater",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "nest",
     "select": [
      [
       { "params": [ "hvac_heater_state" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=", "value": "Kitchen-Hallway" }
     ]
    },
    {
     "alias": "A/C",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "nest",
     "select": [
      [
       { "params": [ "hvac_ac_state" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=", "value": "Kitchen-Hallway" }
     ]
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "humidity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "nest",
     "select": [
      [
       { "params": [ "current_humidity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=", "value": "Kitchen-Hallway" }
     ]
    }
   ]
  },
  {
   "title": "Outside Temperature",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "KBOI Temperature",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "weather",
     "select": [
      [
       { "params": [ "temperature_value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "station",
       "operator": "=",
       "value": "https://api.weather.gov/stations/KBOI"
      }
     ]
    }
   ]
  }
 ]
}